### ISSUE TITLE
Should we use named arguments?

### ISSUE THREAD

**Issue by natebosch** [dart-lang/graphs#7]
Filing for discussion. @jakemac53 - any thoughts?

Initial implementation uses positional arguments for everything. For the algorithms we know we want  to add the arguments which are `Function`s have relatively clear argument and return types, but when looking at the code without getting hints about analyzer errors they aren't super clear. Should we add some named arguments and use `@required` to give analyzer hints that they all need to be included?

before:

```dart
  var components = stronglyConnectedComponents<Node, Node>(
      graph.nodes.keys, (node) => node, (node) => graph.nodes[node] ?? []);
```

after:
```dart
  var components = stronglyConnectedComponents<Node, Node>(
      searchFrom: graph.nodes.keys,
      key: (node) => node,
      children: (node) => graph.nodes[node] ?? []);
```

**Comment by jakemac53** [comment]
I am generally not in favor of using `@required` until/if it becomes a core part of the language.

Imo, the confusion caused by required "optional" parameters is slightly worse than the confusion caused by having to look up what a parameter in a particular position corresponds to.

**Comment by natebosch** [comment]
Fair enough. We can revisit if/when we get a more fully baked `required` named parameters.
